import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import './globals.css'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Kevin Collazos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'mx-auto min-h-screen max-w-[720px] bg-[#1a1a1a] px-6 pt-20 pb-16 text-[#c7c7c7] antialiased',
          GeistSans.className,
        )}
      >
        {children}
      </body>
    </html>
  )
}
