import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import './globals.css';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Kevin Collazos',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'antialiased max-w-[720px] min-h-screen pt-20 pb-16 mx-auto px-6 bg-[#1a1a1a] text-[#c7c7c7]',
          GeistSans.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
